[package]
name = "ums"
version = "0.1.0"
authors = ["Joel Uckelman <uckelman@nomic.net>"]
description = "Vassal User Management Service"
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "^0.7", features = ["http1", "http2", "json", "query", "tokio"] }
axum-extra = { version = "^0.9", features = ["cookie"] }
base64 = "^0.21"
const_format = "^0.2"
digest = { version = "^0.10", features = ["mac"] }
hex = "^0.4"
hmac = "^0.12"
jsonwebtoken = "^9"
mime = "^0.3"
rand = "^0.8"
reqwest = { version = "^0.11", features = ["cookies", "json"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
serde_urlencoded = "^0.7"
sha2 = "^0.10"
thiserror = "^1"
tokio = { version = "^1", features = ["full"] }
tower = { version = "^0.4", features = ["buffer", "limit"] }
tower-http = { version = "^0.5", features = ["cors"] }
urlencoding = "^2"

[dev-dependencies]
wiremock = "^0.6"
