[package]
name = "ums"
version = "0.1.0"
authors = ["Joel Uckelman <uckelman@nomic.net>"]
description = "Vassal User Management Service"
license = "GPL-3.0-or-later"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "^0.7", features = ["http1", "json", "tokio"] }
const_format = "^0.2"
jsonwebtoken = "^9"
mime = "^0.3"
reqwest = { version = "^0.11", features = ["cookies", "json"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tokio = { version = "^1", features = ["full"] }
tower = { version = "^0.4", features = ["buffer", "limit"] }
tower-http = { version = "^0.5", features = ["cors"] }

[dev-dependencies]
wiremock = "^0.6"
